/*
 * File: app/model/ContactUs.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.ContactUs', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'requester_name'
        },
        {
            name: 'requester_email'
        },
        {
            name: 'rerquester_landline'
        },
        {
            name: 'requester_mobile_number'
        },
        {
            name: 'how_to_contact_requester'
        },
        {
            name: 'best_time_to_contact_requester'
        },
        {
            name: 'best_day_to_contact_requester'
        },
        {
            name: 'request'
        },
        {
            name: 'request_time',
            type: 'date'
        },
        {
            name: 'subject',
            type: 'date'
        }
    ]
});