/*
 * File: app/model/Escrow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.Escrow', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'escrow_number'
        },
        {
            name: 'product_id'
        },
        {
            name: 'quote_id'
        },
        {
            name: 'escrow_agreement_file'
        },
        {
            name: 'is_quoted',
            type: 'boolean'
        },
        {
            name: 'is_futuristic',
            type: 'boolean'
        },
        {
            name: 'status'
        },
        {
            name: 'escrow_operation_for'
        },
        {
            name: 'minimum_number_of_product_to_buy',
            type: 'int'
        },
        {
            name: 'whats_product_per_item'
        },
        {
            name: 'quantity',
            type: 'int'
        },
        {
            name: 'total_amount_purchased',
            type: 'float'
        },
        {
            name: 'escrow_initiation_date',
            type: 'date'
        },
        {
            name: 'escrow_acceptance_date',
            type: 'date'
        },
        {
            name: 'escrow_rejection_date',
            type: 'date'
        },
        {
            name: 'escrow_expected_date_of_expiry',
            type: 'date'
        },
        {
            name: 'escrow_initiated_by'
        },
        {
            name: 'escrow_requested_by'
        },
        {
            name: 'escrow_rejected_by'
        },
        {
            name: 'escrow_accepted_by'
        }
    ]
});