/*
 * File: app/model/Future.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.Future', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'future_number'
        },
        {
            name: 'quote_id'
        },
        {
            name: 'future_agreement_file'
        },
        {
            name: 'is_quoted',
            type: 'boolean'
        },
        {
            name: 'is_escrowed',
            type: 'boolean'
        },
        {
            name: 'status'
        },
        {
            name: 'minimum_number_of_product_to_buy',
            type: 'int'
        },
        {
            name: 'whats_product_per_item'
        },
        {
            name: 'quantity',
            type: 'int'
        },
        {
            name: 'total_amount_of_purchase',
            type: 'float'
        },
        {
            name: 'delivery_month'
        },
        {
            name: 'delivery_year'
        },
        {
            name: 'payment_method'
        },
        {
            name: 'staggered_payment_frequency'
        },
        {
            name: 'futures_initiation_date',
            type: 'date'
        },
        {
            name: 'futures_acceptance_date',
            type: 'date'
        },
        {
            name: 'futures_rejection_date',
            type: 'date'
        },
        {
            name: 'futures_expected_date_of_expiry',
            type: 'date'
        },
        {
            name: 'futures_initiated_by'
        },
        {
            name: 'futures_requested_by'
        },
        {
            name: 'futures_rejected_by'
        },
        {
            name: 'futures_accepted_by'
        }
    ]
});