/*
 * File: app/model/HamperHasBeneficiary.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.HamperHasBeneficiary', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'hamper_id'
        },
        {
            name: 'beneficiary_id'
        },
        {
            name: 'status'
        },
        {
            name: 'delivery_type'
        },
        {
            name: 'delivery_is_redirectable',
            type: 'boolean'
        },
        {
            name: 'is_redirected',
            type: 'boolean'
        },
        {
            name: 'amount_paid_for_redirection',
            type: 'float'
        },
        {
            name: 'name_of_actual_receiver_of_the_hamper'
        },
        {
            name: 'place_of_delivery'
        },
        {
            name: 'courier_delivery_comment'
        },
        {
            name: 'beneficiary_delivery_comment'
        },
        {
            name: 'reason_for_hamper_return'
        },
        {
            name: 'date_hamper_was_delivered',
            type: 'date'
        },
        {
            name: 'date_hamper_was_returned',
            type: 'date'
        },
        {
            name: 'delivery_was_made_to'
        },
        {
            name: 'hamper_was_delivered_by'
        },
        {
            name: 'hamper_was_returned_by'
        },
        {
            name: 'number_of_hampers_delivered'
        },
        {
            name: 'is_redirection_confirmed',
            type: 'boolean'
        },
        {
            name: 'date_redirection_was_confirmed',
            type: 'date'
        },
        {
            name: 'redirection_was_confirmed_by'
        },
        {
            name: 'hamper_was_sent_by'
        },
        {
            name: 'country_id'
        },
        {
            name: 'state_id'
        },
        {
            name: 'city_id'
        },
        {
            name: 'delivery_address_option'
        },
        {
            name: 'hamper_container_id'
        }
    ]
});