/*
 * File: app/model/Homepage.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.Homepage', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'image_header_1'
        },
        {
            name: 'image_header_2'
        },
        {
            name: 'image_header_3'
        },
        {
            name: 'image_header_4'
        },
        {
            name: 'products_on_sales'
        },
        {
            name: 'less_than_1000'
        },
        {
            name: 'for_rent'
        },
        {
            name: 'for_options'
        },
        {
            name: 'baby_products'
        },
        {
            name: 'groceries'
        },
        {
            name: 'fashion_and_beauty'
        },
        {
            name: 'office_products'
        },
        {
            name: 'books_and_learning'
        },
        {
            name: 'smartphones'
        },
        {
            name: 'computers'
        },
        {
            name: 'wholesales_and_commodity'
        },
        {
            name: 'home_services'
        },
        {
            name: 'advert_mini_header'
        },
        {
            name: 'primary_books_and_learning'
        },
        {
            name: 'secondary_books_and_learning'
        },
        {
            name: 'tertiary_books_and_learning'
        },
        {
            name: 'professional_books_and_learning'
        },
        {
            name: 'other_books_and_learning'
        },
        {
            name: 'learning_tools_and_learning'
        },
        {
            name: 'all_categories'
        },
        {
            name: 'farming_services'
        }
    ]
});