/*
 * File: app/model/MemberHasMember.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.MemberHasMember', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'member_id'
        },
        {
            name: 'other_member_id'
        },
        {
            name: 'status'
        },
        {
            name: 'relationship'
        },
        {
            name: 'reason_for_suspension'
        },
        {
            name: 'date_connection_was_requested'
        },
        {
            name: 'date_connection_was_accepted'
        },
        {
            name: 'date_connection_was_rejected'
        },
        {
            name: 'date_connection_was_suspended'
        },
        {
            name: 'connection_requested_by'
        },
        {
            name: 'connection_accepted_by'
        },
        {
            name: 'connection_rejected_by'
        },
        {
            name: 'connection_suspended_by'
        }
    ]
});