/*
 * File: app/model/OrderHasProduct.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.OrderHasProduct', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'order_id'
        },
        {
            name: 'product_id'
        },
        {
            name: 'store_id'
        },
        {
            name: 'number_of_portion'
        },
        {
            name: 'amount_saved_per_item_on_this_order'
        },
        {
            name: 'prevailing_retail_selling_price_per_item_at_purchase'
        },
        {
            name: 'cobuy_member_price_per_item_at_purchase'
        },
        {
            name: 'start_price_validity_period'
        },
        {
            name: 'end_price_validity_period'
        },
        {
            name: 'date_ordered',
            type: 'date'
        },
        {
            name: 'date_last_update',
            type: 'date'
        },
        {
            name: 'ordered_by'
        },
        {
            name: 'updated_by'
        },
        {
            name: 'is_hamper',
            type: 'boolean'
        },
        {
            name: 'is_escrow_only',
            type: 'boolean'
        },
        {
            name: 'is_escrow_accepted',
            type: 'boolean'
        },
        {
            name: 'is_quote_only',
            type: 'boolean'
        },
        {
            name: 'is_quote_and_escrow_only',
            type: 'boolean'
        },
        {
            name: 'is_presubscription',
            type: 'boolean'
        },
        {
            name: 'is_presubscription_and_escrow',
            type: 'boolean'
        },
        {
            name: 'is_presubscription_drawdown',
            type: 'boolean'
        },
        {
            name: 'is_postsubscription',
            type: 'boolean'
        },
        {
            name: 'is_postsubscription_and_escrow',
            type: 'boolean'
        },
        {
            name: 'is_mainstore',
            type: 'boolean'
        },
        {
            name: 'quote_id',
            type: 'int'
        },
        {
            name: 'escrow_id',
            type: 'int'
        },
        {
            name: 'hamper_terms_and_condition',
            type: 'boolean'
        },
        {
            name: 'future_trading',
            type: 'boolean'
        },
        {
            name: 'month_of_delivery',
            type: 'string'
        },
        {
            name: 'year_of_delivery',
            type: 'string'
        },
        {
            name: 'payment_frequency',
            type: 'string'
        },
        {
            name: 'initial_payment_rate',
            type: 'float'
        },
        {
            name: 'decision',
            type: 'boolean'
        },
        {
            name: 'minimum_paas_duration',
            type: 'int'
        },
        {
            name: 'maximum_paas_duration',
            type: 'int'
        },
        {
            name: 'actual_paas_duration',
            type: 'int'
        }
    ]
});