/*
 * File: app/model/Order.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.Order', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'order_number'
        },
        {
            name: 'status'
        },
        {
            name: 'order_domain_id'
        },
        {
            name: 'order_initiation_date'
        },
        {
            name: 'last_updated_date'
        },
        {
            name: 'order_initiated_by'
        },
        {
            name: 'order_updated_by'
        }
    ]
});