/*
 * File: app/model/ProductType.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.ProductType', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'name'
        },
        {
            name: 'category_id'
        },
        {
            name: 'description'
        },
        {
            name: 'code'
        },
        {
            name: 'vat_rate'
        },
        {
            name: 'sales_tax_rate'
        },
        {
            name: 'vat_rate_commencement_date'
        },
        {
            name: 'sales_tax_rate_commencement_date'
        },
        {
            name: 'create_time'
        },
        {
            name: 'update_time'
        },
        {
            name: 'create_user_id'
        },
        {
            name: 'update_user_id'
        },
        {
            name: 'is_available',
            type: 'boolean'
        },
        {
            name: 'is_paas',
            type: 'boolean'
        },
        {
            name: 'monthly_paas_subscription_cost',
            type: 'float'
        },
        {
            name: 'minimum_quantity_for_paas_subscription',
            type: 'int'
        },
        {
            name: 'maxumum_quantity_for_paas_subscription',
            type: 'int'
        },
        {
            name: 'icon'
        },
        {
            name: 'minimum_paas_duration',
            type: 'int'
        },
        {
            name: 'maximum_paas_duration',
            type: 'int'
        }
    ]
});