/*
 * File: app/model/Quote.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.Quote', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'quote_number'
        },
        {
            name: 'product_id'
        },
        {
            name: 'quote_file'
        },
        {
            name: 'is_escrowed',
            type: 'boolean'
        },
        {
            name: 'is_for_future',
            type: 'boolean'
        },
        {
            name: 'is_already_accepted',
            type: 'boolean'
        },
        {
            name: 'status'
        },
        {
            name: 'minimum_number_of_product_to_buy',
            type: 'int'
        },
        {
            name: 'whats_product_per_item'
        },
        {
            name: 'quantity',
            type: 'int'
        },
        {
            name: 'total_amount_quoted',
            type: 'float'
        },
        {
            name: 'quote_initiation_date',
            type: 'date'
        },
        {
            name: 'quote_acceptance_date',
            type: 'date'
        },
        {
            name: 'quote_rejection_date',
            type: 'date'
        },
        {
            name: 'quote_expected_date_of_expiry',
            type: 'date'
        },
        {
            name: 'quote_submission_date_of_expiry',
            type: 'date'
        },
        {
            name: 'quote_initiated_by'
        },
        {
            name: 'quote_submitted_by'
        },
        {
            name: 'quote_rejected_by'
        },
        {
            name: 'quote_accepted_by'
        }
    ]
});