/*
 * File: app/model/QuoteHasResponse.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.QuoteHasResponse', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'quote_id'
        },
        {
            name: 'member_id'
        },
        {
            name: 'status'
        },
        {
            name: 'is_quote_escrowed',
            type: 'boolean'
        },
        {
            name: 'is_quote_for_future',
            type: 'boolean'
        },
        {
            name: 'is_escrow_terms_accepted',
            type: 'boolean'
        },
        {
            name: 'is_future_facility_terms_accepted',
            type: 'boolean'
        },
        {
            name: 'is_platform_quotation_terms_accepted',
            type: 'boolean'
        },
        {
            name: 'quotation_file'
        },
        {
            name: 'video_filename'
        },
        {
            name: 'total_amount_quoted',
            type: 'float'
        },
        {
            name: 'date_quotation_was_sent',
            type: 'date'
        },
        {
            name: 'quotation_sent_by'
        },
        {
            name: 'is_with_video',
            type: 'boolean'
        }
    ]
});