/*
 * File: app/model/Voucher.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.Voucher', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'voucher_number'
        },
        {
            name: 'status'
        },
        {
            name: 'voucher_type'
        },
        {
            name: 'voucher_value'
        },
        {
            name: 'purpose'
        },
        {
            name: 'remaining_voucher_value'
        },
        {
            name: 'topup_value_status'
        },
        {
            name: 'topup_value'
        },
        {
            name: 'remaining_voucher_share_in_percentage'
        },
        {
            name: 'accepted_voucher_creation_and_user_terms',
            type: 'boolean'
        },
        {
            name: 'topup_date'
        },
        {
            name: 'toppedup_by'
        },
        {
            name: 'date_created'
        },
        {
            name: 'date_confirmed'
        },
        {
            name: 'date_updated'
        },
        {
            name: 'create_by'
        },
        {
            name: 'confirmed_by'
        },
        {
            name: 'topup_confimed_by'
        },
        {
            name: 'updated_by'
        },
        {
            name: 'accepted_voucher_topup_terms',
            type: 'boolean'
        },
        {
            name: 'is_voucher_toppedup',
            type: 'boolean'
        },
        {
            name: 'is_voucher_payment_confirmed',
            type: 'boolean'
        },
        {
            name: 'is_topup_payment_confirmed',
            type: 'boolean'
        },
        {
            name: 'date_topup_confirmed',
            type: 'date'
        }
    ]
});