/*
 * File: app/model/VoucherLimitedToCategory.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cobuy.model.VoucherLimitedToCategory', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'voucher_id'
        },
        {
            name: 'category_id'
        },
        {
            name: 'status'
        },
        {
            name: 'date_limit_was_added_placed'
        },
        {
            name: 'date_limi_was_updated'
        },
        {
            name: 'voucher_limit_was_placed_by'
        },
        {
            name: 'voucher_limit_was_updated_by'
        },
        {
            name: 'expendable_limits_in_percentage'
        }
    ]
});